### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by samuelpatro** [josex2r/markdown-toolbar#1]
Using Seti and Base16Tomorrow Dark syntax themes
Atom version: 1.9.0-beta0
![miss](https://cloud.githubusercontent.com/assets/3110002/16942740/06883b68-4d98-11e6-8d7d-73634af3f8d6.png)

**Comment by hidezember** [comment]
I got the same issue too,
Using One Dark UI/syntax themes
Atom version: 1.8.0

**Comment by JalonWong** [comment]
me too
Atom version: 1.8.0

**Comment by josex2r** [comment]
Must check in other editors/computers.
Currently using 1.8.0 and it works for me.

**Comment by JasonOwen** [comment]
I found I was missing the tool-bar package and the markdown-writer package. After installing the tool-bar package icons appeared correctly.

**Comment by hidezember** [comment]
Yep，when I added the  [tool-bar package](https://github.com/suda/tool-bar)，it appeared correctly.
Maybe the owner should wirte this note in the README.md

**Comment by josex2r** [comment]
The plugin doesn't have dependencies with the markdown-toolbar package, but I think the font-awesome lib is not being loaded correctly in my plugin.

Maybe it's a css problem,  thanks for the info :)

**Comment by amelkikh** [comment]
Could you please fix this problem?
